# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Build"

on:
  pull_request:
  push:
    branches:
      - "2.x"

permissions:
  contents: read

jobs:
  coding-standard:
    name: "Coding Standard"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        extension-name:
          - "phpstan-doctrine"
          - "extension-installer"
          - "phpstan-phpunit"
          - "phpstan-mockery"
          - "phpstan-symfony"
          - "phpdoc-parser"
          - "phpstan-nette"
          - "phpstan-webmozart-assert"
          - "phpstan-beberlei-assert"
          - "phpstan-deprecation-rules"
          - "phpstan-dibi"
          - "phpstan-strict-rules"
          - "phpstan-src"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit

      - name: "Checkout extension"
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          repository: "phpstan/${{ matrix.extension-name }}"

      - name: "Checkout build-cs"
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          path: "build-cs"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962" # 2.40.0
        with:
          coverage: "none"
          php-version: "8.2"

      - name: "Install dependencies"
        working-directory: "build-cs"
        run: "composer install --no-interaction --no-progress"

      - name: "Coding Standard"
        run: "make cs"
